# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

stages:
  - stage: Buildwebapp
    jobs:
      - job: Buildwebapp

        steps:
          - task: PublishBuildArtifacts@1
            inputs:
              PathtoPublish: '$(Build.ArtifactStagingDirectory)'
              ArtifactName: 'drop'
              publishLocation: 'Container'

  - stage: Deploywebapp
    jobs:
      - job: deploywebapp
        steps:
          - task: AzureRmWebAppDeployment@4
            inputs:
              ConnectionType: 'AzureRM'
              azureSubscription: 'azure-sub-connection'
              appType: 'webApp'
              WebAppName: 'shailenderwebapp'
              packageForLinux: '$(Build.ArtifactStagingDirectory)/*.zip'