# Starter pipeline

# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool: nodepool
steps:

- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(System.DefaultWorkingDirectory)' 
    includeRootFolder: false 
    archiveType: 'zip' # Options: zip, 7z, tar, wim
    tarCompression: 'gz' # Optional. Options: gz, bz2, xz, none
    archiveFile: '$(System.DefaultWorkingDirectory)/$(Build.BuildId).zip' 
  
- task: AzureWebApp@1
  inputs:
    azureSubscription: 'AppServiceConnection'
    appType: 'webApp'
    appName: 'hakiatc'
    package: '$(System.DefaultWorkingDirectory)/*.zip'
    deploymentMethod: 'auto'



